### ISSUE TITLE
An error occurs when trying to launch the asset browser.

### ISSUE THREAD

**Issue by stalker168** [djmonkeyuk/nms-base-builder#76]
An error occurs when trying to launch the asset browser.
```
Error: Python: Traceback (most recent call last):
  File "C:\Users\Vladimir\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\no_mans_sky_base_builder\__init__.py", line 1245, in execute
bpy.ops.wm.bpy_externall_server(speed=0.15, mode="start")
  File "D:\SteamLibrary\steamapps\common\Blender\3.1\scripts\modules\bpy\ops.py", line 132, in __call__
ret = _op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.wm.bpy_externall_server" error, could not be found
location: :-1
```
![image](https://user-images.githubusercontent.com/31571343/166114053-9f3461d3-3f69-4936-9f97-4e175b06ea65.png)

**Comment by charliebanks** [comment]
Please install the necessary add-ons as described in the read me instructions :)
